[package]
name = "bnz"
description = "banzai - a libre bzip2 encoder (cli)"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
banzai = { path = "../" }

[[bin]]
path = "src/main.rs"
name = "bnz"
